public class Day1Assignment {
    public static void main(String[] args){

        System.out.println("Hello");
        System.out.println("The list of integers are:");
        int a=1;
        int b=2;
        int c=3;
        int d=4;
        int e=5;
        int f=6;
        int g=7;
        int h=8;
        int i=9;
        int j=10;
        System.out.println(a);
        System.out.println(b);
        System.out.println(c);
        System.out.println(d);
        System.out.println(e);
        System.out.println(f);
        System.out.println(g);
        System.out.println(h);
        System.out.println(i);
        System.out.println(j);

        System.out.println("The list of double are:");
        double a1=1.23456789;
        double b1=2.23456789;
        double c1=3.23456789;
        double d1=4.23456789;
        double e1=5.23456789;
        double f1=6.23456789;
        double g1=7.23456789;
        double h1=8.23456789;
        double i1=9.23456789;
        double j1=10.23456789;
        System.out.println(a1);
        System.out.println(b1);
        System.out.println(c1);
        System.out.println(d1);
        System.out.println(e1);
        System.out.println(f1);
        System.out.println(g1);
        System.out.println(h1);
        System.out.println(i1);
        System.out.println(j1);

        System.out.println("The list of float are:");
        float a2=11.22f;
        float b2=12.22f;
        float c2=13.22f;
        float d2=14.22f;
        float e2=15.22f;
        float f2=16.22f;
        float g2=17.22f;
        float h2=18.22f;
        float i2=19.22f;
        float j2=20.22f;
        System.out.println(a2);
        System.out.println(b2);
        System.out.println(c2);
        System.out.println(d2);
        System.out.println(e2);
        System.out.println(f2);
        System.out.println(g2);
        System.out.println(h2);
        System.out.println(i2);
        System.out.println(j2);

        System.out.println("The value of long are:");
        long a3=12345678910l;
        long b3=22345678910l;
        long c3=32345678910l;
        long d3=42345678910l;
        long e3=52345678910l;
        long f3=62345678910l;
        long g3=72345678910l;
        long h3=82345678910l;
        long i3=92345678910l;
        long j3=102345678910l;
        System.out.println(a3);
        System.out.println(b3);
        System.out.println(c3);
        System.out.println(d3);
        System.out.println(e3);
        System.out.println(f3);
        System.out.println(g3);
        System.out.println(h3);
        System.out.println(i3);
        System.out.println(j3);

        System.out.println("The value of short are:");
        short a4=1234;
        short b4=2234;
        short c4=3234;
        short d4=4234;
        short e4=5234;
        short f4=6234;
        short g4=7234;
        short h4=8234;
        short i4=9234;
        short j4=10234;
        System.out.println(a4);
        System.out.println(b4);
        System.out.println(c4);
        System.out.println(d4);
        System.out.println(e4);
        System.out.println(f4);
        System.out.println(g4);
        System.out.println(h4);
        System.out.println(i4);
        System.out.println(j4);

        System.out.println("The value of byte are:");
        byte a5=12;
        byte b5=13;
        byte c5=14;
        byte d5=15;
        byte e5=16;
        byte f5=17;
        byte g5=18;
        byte h5=19;
        byte i5=20;
        byte j5=21;
        System.out.println(a5);
        System.out.println(b5);
        System.out.println(c5);
        System.out.println(d5);
        System.out.println(e5);
        System.out.println(f5);
        System.out.println(g5);
        System.out.println(h5);
        System.out.println(i5);
        System.out.println(j5);

        System.out.println("The characters are:");
        char a6='A';
        char b6='B';
        char c6='C';
        char d6='D';
        char e6='E';
        char f6='F';
        char g6='G';
        char h6='H';
        char i6='I';
        char j6='J';
        System.out.println(a6);
        System.out.println(b6);
        System.out.println(c6);
        System.out.println(d6);
        System.out.println(e6);
        System.out.println(f6);
        System.out.println(g6);
        System.out.println(h6);
        System.out.println(i6);
        System.out.println(j6);


    }

}
